services:

  azure-functions-usuarios-roles:
    image: azure-functions-usuarios-roles:latest
    container_name: azure-functions-usuarios-roles
    ports:
      - "7071:80"
    env_file:
      - .env

  bff-usuarios-roles:
    image: bff-usuarios-roles:latest
    container_name: bff-usuarios-roles
    ports:
      - "8080:8080"
    environment:
      USUARIOS_SERVICE_URL: http://azure-functions-usuarios-roles
      ROLES_SERVICE_URL: http://azure-functions-usuarios-roles
    depends_on:
      - azure-functions-usuarios-roles