CREATE TABLE roles (
    id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(200)
);

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(120) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    id_rol NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
);

INSERT INTO roles (nombre, descripcion)
VALUES ('ADMIN', 'Administrador del sistema');

INSERT INTO roles (nombre, descripcion)
VALUES ('USUARIO', 'Usuario estándar');

INSERT INTO usuarios (nombre, email, password, id_rol, estado)
VALUES ('Admin Principal', 'admin@cloudnative.cl', 'admin123', 1, 'ACTIVO');

INSERT INTO usuarios (nombre, email, password, id_rol, estado)
VALUES ('Usuario Demo', 'usuario@cloudnative.cl', 'usuario123', 2, 'ACTIVO');

COMMIT;